# Define your website routes here
#controllers:
#    resource: ../src/Controller/Website/
#    type: attribute

#static:
#    path: /static-route
#    controller: App\Controller\DefaultController::index

login_explainer:
    path: /login_explainer
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: login/explainer.html.twig

# Search controller
sulu_search:
    resource: '@SuluSearchBundle/config/routing_website.yaml'
